import unittest
from unittest.mock import patch

from app.assistant import AssistantResponse
from app.demo import run_demo


class DemoTests(unittest.TestCase):
    def test_retrieval_demo_exposes_ranking_and_agent_payload(self) -> None:
        output = run_demo(
            mode="retrieval",
            model_name="qwen3:4b",
            question="What is GraphQL?",
        )

        self.assertIn("1. RETRIEVAL", output)
        self.assertIn("graphql.txt", output)
        self.assertIn("Generated by model: False", output)
        self.assertIn("3. AGENT-READY OUTPUT", output)
        self.assertIn('"sources": [', output)

    @patch("app.demo.ArchitectureAssistant.answer")
    def test_ollama_warning_is_visible_in_demo(
        self,
        answer: object,
    ) -> None:
        answer.return_value = AssistantResponse(
            content="Retrieval fallback.",
            sources=("aws.txt",),
            generated_by_model=False,
            answer_mode="retrieval_fallback",
            warning="Ollama unavailable.",
        )

        output = run_demo(
            mode="ollama",
            model_name="qwen3:4b",
            question="What is AWS?",
        )

        self.assertIn("3. FALLBACK WARNING", output)
        self.assertIn("4. AGENT-READY OUTPUT", output)
        self.assertIn("Ollama unavailable.", output)


if __name__ == "__main__":
    unittest.main()
