import argparse
import json

from app.assistant import ArchitectureAssistant
from app.models import OllamaModel
from app.retriever import SearchResult, search

DEFAULT_QUESTION = (
    "Explain how AWS Step Functions participates in an "
    "event-driven architecture."
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Run a repeatable Architecture Assistant demo."
    )
    parser.add_argument(
        "--mode",
        choices=("retrieval", "ollama"),
        default="ollama",
        help="Use lexical retrieval only or full local RAG.",
    )
    parser.add_argument(
        "--model",
        default="qwen3:4b",
        help="Ollama model used in ollama mode.",
    )
    parser.add_argument(
        "--question",
        default=DEFAULT_QUESTION,
        help="Architecture question used in the demo.",
    )
    return parser


def format_result(index: int, result: SearchResult) -> str:
    chunk = result.chunk
    return (
        f"{index}. {chunk.source} | topic={chunk.topic} | "
        f"chunk={chunk.chunk_index} | score={result.score:.2f}\n"
        f"   {chunk.content}"
    )


def run_demo(mode: str, model_name: str, question: str) -> str:
    results = search(question, limit=2)
    model = OllamaModel(model=model_name) if mode == "ollama" else None
    assistant = ArchitectureAssistant(model=model, retrieval_limit=2)
    response = assistant.answer(question)

    sections = [
        "=== Local Architecture Assistant Demo ===",
        (
            f"Mode: {mode}\n"
            f"Model: {model_name if model else 'none'}\n"
            f"Question: {question}"
        ),
        "1. RETRIEVAL\n"
        + (
            "\n\n".join(
                format_result(index, result)
                for index, result in enumerate(results, start=1)
            )
            if results
            else "No local chunks matched."
        ),
        (
            "2. GROUNDED RESPONSE\n"
            f"{response.content}\n\n"
            f"Sources: {', '.join(response.sources) or 'none'}\n"
            f"Generated by model: {response.generated_by_model}\n"
            f"Answer mode: {response.answer_mode}"
        ),
    ]

    if response.warning:
        sections.append(f"3. FALLBACK WARNING\n{response.warning}")

    agent_output_step = 4 if response.warning else 3
    agent_payload = {
        "content": response.content,
        "sources": list(response.sources),
        "generated_by_model": response.generated_by_model,
        "answer_mode": response.answer_mode,
        "warning": response.warning,
    }
    sections.append(
        f"{agent_output_step}. AGENT-READY OUTPUT\n"
        + json.dumps(agent_payload, indent=2, ensure_ascii=True)
    )

    return "\n\n".join(sections)


def main() -> None:
    args = build_parser().parse_args()
    print(run_demo(args.mode, args.model, args.question))


if __name__ == "__main__":
    main()
